###
GET http://localhost:5555/api
Content-Type: application/json

###
GET http://localhost:5555/api/test
Content-Type: application/json

###
POST http://localhost:5555/api/paok
Content-Type: application/json

{
  "body2": "asdasdasdasd"
}

###
GET http://localhost:5555/api/check/3244?you=22&me=256
Content-Type: application/json

{
  "to_body": "asdasdasd2d2"
}